<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SK3D42E8" failures="1" tests="5" name="Account Test Cases" time="3.207" errors="0" timestamp="2024-12-30T09:10:37 SAST">
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyDepositSuccessfulMessage" time="0.679"/>
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyAmountDepositedSuccessfully" time="0.255"/>
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyWithdrawlSuccessfulMessage" time="1.383"/>
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyWithdrawlAmountMoreThanBalance" time="0.209">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Transaction Failed. You can not withdraw amount more than the balance.] but found [Transaction successful]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Transaction Failed. You can not withdraw amount more than the balance.] but found [Transaction successful]
at com.BankingApp.TestCases.AccountTestCases.verifyWithdrawlAmountMoreThanBalance(AccountTestCases.java:143)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyWithdrawlAmountMoreThanBalance -->
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyAmountwithdrawnSuccessfully" time="0.248"/>
</testsuite> <!-- Account Test Cases -->
