<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-SK3D42E8" failures="1" tests="1" name="Account Test Cases(failed)" time="1.909" errors="0" timestamp="2024-12-20T08:14:42 SAST">
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyWithdrawlAmountMoreThanBalance" time="1.112">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Transaction Failed. You can not withdraw amount more than the balance.] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Transaction Failed. You can not withdraw amount more than the balance.] but found [null]
at com.BankingApp.TestCases.AccountTestCases.verifyWithdrawlAmountMoreThanBalance(AccountTestCases.java:146)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyWithdrawlAmountMoreThanBalance -->
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyAmountwithdrawnSuccessfully" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAmountwithdrawnSuccessfully -->
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyWithdrawlSuccessfulMessage" time="0.0">
    <ignored/>
  </testcase> <!-- verifyWithdrawlSuccessfulMessage -->
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyDepositSuccessfulMessage" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDepositSuccessfulMessage -->
  <testcase classname="com.BankingApp.TestCases.AccountTestCases" name="verifyAmountDepositedSuccessfully" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAmountDepositedSuccessfully -->
</testsuite> <!-- Account Test Cases(failed) -->
